name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get the Git commit hash
        id: commit_hash
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Build the Docker image
        run: docker build 2-automation --file 2-automation/Dockerfile --tag botondopra22/java_app:${{ env.COMMIT_HASH }} --tag botondopra22/java_app:latest
        
      - name: Push Docker image to Docker registry
        run: |
          docker login -u ${{secrets.DOCKER_USERNAME}} -p "${{secrets.DOCKER_PASSWORD}}"
          docker push botondopra22/java_app --all-tags
